"""empty message

Revision ID: 2dde0738c0a6
Revises: 643ba32d13a7
Create Date: 2017-08-27 16:37:33.209000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dde0738c0a6'
down_revision = '643ba32d13a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'author_id')
    # ### end Alembic commands ###
