"""empty message

Revision ID: 643ba32d13a7
Revises: f0a11d45384a
Create Date: 2017-08-27 16:25:52.726000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643ba32d13a7'
down_revision = 'f0a11d45384a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    # ### end Alembic commands ###
